apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxtjs
  namespace: aks-architect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aks-architect-nuxtjs
  template:
    metadata:
      labels:
        app: aks-architect-nuxtjs
    spec:
      nodeSelector:
        workloadType: user
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: aks-architect-nuxtjs
      containers:
      - name: aks-architect-nuxtjs
        image: aksarchitect.azurecr.io/frontend:${IMAGE_TAG}
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "3000"
        - name: APP_BUILD_SHA
          value: ${APP_BUILD_SHA}
        - name: NODE_ENV
          value: production
        resources:
          limits:
            cpu: 0.5
            memory: 512Mi
          requests:
            cpu:  0.25
            memory: 256Mi
