name: 'Determine Tags'
description: 'Figures out Docker tag name variations based on conventions and git shas'
inputs:
  devBase:
    description: 'Base name of dev tag. Defaults to dev'
    required: true
    default: 'dev'
  stagingBase:
    description: 'Base name of staging tag. Defaults to staging'
    required: true
    default: 'staging'
outputs:
  git-sha:
    description: 'Short version of current git sha'
    value: ${{ steps.set-tag.outputs.sha }}
  dev-tag:
    description: 'Dev Tag'
    value: ${{ steps.set-tag.outputs.dev }}
  staging-tag:
    description: 'Staging Tag'
    value: ${{ steps.set-tag.outputs.staging }}
  # TODO - production?

runs:
  using: 'composite'
  steps:
  - id: git-sha
    name: save git sha
    shell: bash
    run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

  - id: set-tag
    name: save dev and staging tag variants
    shell: bash
    run: |
      echo "::set-output name=sha::${{ env.sha }}"
      echo "::set-output name=dev::${{ inputs.devBase }}-${{ env.sha }}"
      echo "::set-output name=staging::${{ inputs.stagingBase }}-${{ env.sha }}"


  - id: test-branch
    if: github.ref == 'refs/heads/feat/kustomize'
    run: echo "has branch ref"