name: config

# CONFIG GOES HERE
env:
  dev-cluster-name: 'cloudkube-dev-r9er' # cloudkube-dev-r9er-cluster
  dev-resource-group: 'cloudkube-dev-r9er-rg'
  dev-url: 'https://aks-architect.dev.cloudkube.io/'

on:
  workflow_call:
    outputs:
      target:
        description: ''
        value: ${{ jobs.setup-variables.outputs.target }}
      cluster:
        description: ''
        value: ${{ jobs.setup-variables.outputs.cluster }}
      resource-group:
        description: ''
        value: ${{ jobs.setup-variables.outputs.resource-group }}
      url:
        description: ''
        value: ${{ jobs.setup-variables.outputs.url }}

jobs:
  setup-variables:
    runs-on: ubuntu-latest
    outputs:
      target:         ${{ steps.resolved.outputs.target }}
      cluster:        ${{ steps.resolved.outputs.cluster }}
      resource-group: ${{ steps.resolved.outputs.resource-group }}
      url:            ${{ steps.resolved.outputs.url }}

    steps:
    - id: is-dev
      if: github.ref == 'refs/heads/feat/kustomize' # <==== CONFIGURE
      shell: bash
      run: |
        echo "target=dev" >> $GITHUB_ENV
        echo "cluster=${{ env.dev-cluster-name }}" >> $GITHUB_ENV
        echo "rg=${{ env.dev-resource-group }}" >> $GITHUB_ENV
        echo "url=${{ env.dev-url }}" >> $GITHUB_ENV

    - id: resolved
      shell: bash
      run: |
        echo "::set-output name=target::${{ env.target }}"
        echo "::set-output name=cluster::${{ env.cluster }}"
        echo "::set-output name=resource-group::${{ env.rg }}"
        echo "::set-output name=url::${{ env.url }}"
