name: docker-build

# Example Tags e.g. `dev-abc123` vs `0.2.0`
# Note: dev and staging branch names are defined in build-and-push job.

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      git-sha:
        type: string
        default: 'maybe-should-be-requried'
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZ_APPINSIGHTS_CONNECTION_STRING:
        required: true
      AZ_DEFENDER_TOKEN:
        required: true

# ===============
#  Configuration
# ===============
env:
  acr-registry: aksarchitect
  image-name: aksarchitect.azurecr.io/frontend

jobs:
  build-and-push:
    # if: inputs.environment == 'feat/defender-scan' # only dev exists as environment
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v2
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - run: az acr login --name ${{ env.acr-registry }}

    # Build Dev Image
    - name: 'Docker - Build'
      # if: inputs.environment == 'dev'
      run: docker build -t ${{ env.image-name }}:dev-${{ inputs.git-sha }} .

    - uses: Azure/container-scan@v0
      name: 'Docker - Azure Defender Scan'
      # if: inputs.environment == 'dev'
      continue-on-error: true
      id: container-scan
      with:
        image-name: ${{ env.image-name }}:dev-${{ inputs.git-sha }}
        severity-threshold: WARN

    # Push Dev Image
    - name: 'Docker - Push'
      # if: inputs.environment == 'dev'
      run: docker push ${{ env.image-name }}:dev-${{ inputs.git-sha }}

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with:
        scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_DEFENDER_TOKEN }}

    - run: docker logout


  promote-to-staging:
    if: inputs.environment == 'staging'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - run: az acr login --name ${{ env.acr-registry }}

    # Promote Dev to Staging
    - name: 'Re-tag to Promote'
      run: |
        docker pull ${{ env.image-name }}:dev-${{ inputs.git-sha }}
        docker tag ${{ env.image-name }}:dev-${{ inputs.git-sha }} ${{ env.image-name }}:staging-${{ inputs.git-sha }}
        docker push ${{ env.image-name }}:staging-${{ inputs.git-sha }}

    - run: docker logout
