name: ci

on:
  push:
    branches:
    - main
    - feat/*
    - fix/*
    paths-ignore:
    - '.github/**'
    - 'content/**'
    - 'manifests/**'
    - 'scss/**'
    - 'static/**'
    - '**/*.md'
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: npm install
      run: npm ci

    - name: audit dependences
      run: npm audit --audit-level=moderate
      continue-on-error: true

    - name: lint
      run: npm run lint

    - name: unit tests
      run: npm run test

    - name: build
      run: npm run nuxt:build

  docker:
    needs: node
    runs-on: ubuntu-latest
    steps:
    - run: docker build .
