name: dev

on:
  push:
    branches:
    # - main
    - feat/kustomize

permissions:
  id-token: write
  contents: read

jobs:
  tag-conventions:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.determine-tags.outputs.git-sha }}
      dev: ${{ steps.determine-tags.outputs.dev-tag }}
      staging: ${{ steps.determine-tags.outputs.staging-tag }}
    steps:
    - uses: actions/checkout@v2
    - id: determine-tags
      uses: ./.github/actions/tag-conventions
    # - run: echo sha ${{ steps.determine-tags.outputs.git-sha }}
    # - run: echo dev-tag ${{ steps.determine-tags.outputs.dev-tag }}
    # - run: echo staging-tag ${{ steps.determine-tags.outputs.staging-tag }}

  docker:
    needs: tag-conventions
    uses: ./.github/workflows/job-docker.yaml
    with:
      environment: dev
      dev-tag: ${{ needs.tag-conventions.outputs.dev }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  # deploy:
  #   uses: ./.github/workflows/job-deploy.yaml
  #   with:
  #     environment: dev
  #     resource-group: cloudkube-dev-r9er-rg
  #     cluster-name: cloudkube-dev-r9er-cluster
  #     overlays: ./manifests/overlays/dev
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
