name: dev

on:
  push:
    branches:
    # - main
    - feat/kustomize

permissions:
  id-token: write
  contents: read

env:
  deployment-url: 'https://aks-architect.dev.cloudkube.io/'

jobs:
  tags:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.patterns.outputs.git-sha }}
      dev: ${{ steps.patterns.outputs.dev-tag }}
      staging: ${{ steps.patterns.outputs.staging-tag }}
    steps:
    - uses: actions/checkout@v2
    - id: patterns
      uses: ./.github/actions/tag-conventions

  # docker:
  #   needs: tags
  #   uses: ./.github/workflows/job-docker.yaml
  #   with:
  #     environment: dev
  #     dev-tag: ${{ needs.tags.outputs.dev }}
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy:
    needs: tags
    uses: ./.github/workflows/job-deploy.yaml
    with:
      environment: dev
      git-sha: ${{ needs.tags.outputs.sha }}
      image-tag: ${{ needs.tags.outputs.dev }}
      resource-group: cloudkube-dev-r9er-rg
      cluster-name:   cloudkube-dev-r9er-cluster
      overlays: ./manifests/overlays/dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  e2e:
    needs: tags
    runs-on: ubuntu-latest
    env:
      SELENIUM_TARGET_URL: ${{ env.deployment-url }}
      APP_BUILD_SHA: ${{ needs.tags.outputs.sha }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
        npm ci
        npm install chromedriver --chromedriver_version=LATEST
    - run: npm run confirm-deployment
      continue-on-error: true
    - run: npm run confirm-deployment
