name: dev

on:
  push:
    branches:
    # - main
    - feat/kustomize

permissions:
  id-token: write
  contents: read

jobs:
  config:
    uses: ./.github/workflows/_config.yaml

  confirm-target:
    needs: config
    runs-on: ubuntu-latest
    steps:
    - run: echo target ${{ needs.config.outputs.target }}
    - run: echo cluster ${{ needs.config.outputs.cluster }}
    - run: echo git sha ${{ needs.config.outputs.git-sha }}
    - run: echo docker tag ${{ needs.config.outputs.docker-tag }}

  docker:
    needs: config
    uses: ./.github/workflows/_docker.yaml
    with:
      environment:  ${{ needs.config.outputs.target }}
      git-sha:      ${{ needs.config.outputs.git-sha }}
    secrets:
      AZURE_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy:
    needs: config
    uses: ./.github/workflows/_deploy.yaml
    with:
      environment:    ${{ needs.config.outputs.target }}
      git-sha:        ${{ needs.config.outputs.git-sha }}
      image-tag:      ${{ needs.config.outputs.docker-tag }}
      resource-group: ${{ needs.config.outputs.resource-group }}
      cluster-name:   ${{ needs.config.outputs.cluster }}
      hostname:       ${{ needs.config.outputs.hostname }}
      overlays:       ./manifests/overlays/${{ needs.config.outputs.target }}
    secrets:
      AZURE_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  e2e:
    needs: [config, docker, deploy]
    uses: ./.github/workflows/_e2e.yaml
    with:
      url:       ${{ needs.config.outputs.url }}
      build-sha: ${{ needs.config.outputs.git-sha }}
