name: docker-build

# Example Tags e.g. `dev-abc123` vs `0.2.0`
# Note: dev and staging branch names are defined in build-and-push job.

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      dev-tag:
        type: string
        default: 'dev-unknown'
      staging-tag:
        type: string
        default: 'staging-unknown'
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

# ===============
#  Configuration
# ===============
env:
  azureRegistryName: aksarchitect
  imageName: aksarchitect.azurecr.io/frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

    - uses: actions/checkout@v2
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Container Registry - Login'
      run: az acr login --name ${{ env.azureRegistryName }}

    # === Build Image (Dev) ===
    - name: 'Docker - Build and Push'
      if: github.ref == 'refs/heads/feat/kustomize' # DEV branch <================ Temp!
      run: |
        docker build -t ${{ inputs.dev-tag }} .
        docker push ${{ inputs.dev-tag }}

    # === Promote Image (Staging) ===
    - name: 'Re-tag to Promote'
      if: github.ref == 'refs/heads/staging' # STAGING branch
      run: |
        docker pull ${{ inputs.dev-tag }}
        docker tag ${{ inputs.dev-tag }} ${{ inputs.staging-tag }}
        docker push ${{ inputs.staging-tag }}

    - name: 'Docker - Logout'
      run: docker logout
